<?php
use Jodit\Application;

class JoditRestTestApplication extends Application {
	public function errorHandler($errorNumber, $errorMessage, $file, $line) {
//		var_export($this->config);
		parent::errorHandler($errorNumber, $errorMessage, $file, $line); // TODO: Change the autogenerated stub
	}

	function checkPermissions() {
        if (!in_array(@$_SERVER['REMOTE_ADDR'], ['127.0.0.1', '::1']) or isset($_GET['auth'])) {
            throw new ErrorException('Need authorization', 403);
        }
    }
}